"""Add progress column to backup_jobs

Revision ID: 665ba8516d45
Revises: 125fca0d3e4a
Create Date: 2024-08-22 17:22:18.757859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665ba8516d45'
down_revision: Union[str, None] = '125fca0d3e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_jobs', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup_jobs', 'progress')
    # ### end Alembic commands ###
